### ISSUE TITLE
dev:ios does not hot reload nor rebuild app on simulator

### ISSUE THREAD

**Issue by jkt3000** [drannex42/svelte-capacitor#13] opened 2021-07-22 15:44 UTC
In previous version, running ```npm run dev:ios``` would launch servers on port 5000 and 5001 and allow ios simulator to hot reload content when you make changes to source code, same as you would get on a local web browser.

In this new version, running ```npm run dev:ios``` and running the simulator will load the app, but any changes to source code does nothing on the simulator - code changes do not appear, even if on web browser changes are reflected immediately (ie: I have local web browser running my svelte page as well as the Xcode ios simulator - changes appear on the web browser but not on the IOS).

In fact, even stopping and restarting ```npm run dev:ios``` does not update changes on the ios simulator. No changes are reflected until you type ```npm run build:ios```

In the previous version, the package.json scripts included running a server on port 5000 as well as another server on port 5001. In this version, I only see script that runs vite on port 5000. However, in the ```capacitor.config.json``` the server has the line ```"url": "http://change-me:5001"``` - but I notice nothing running on port 5001 in the ```package.json``` scripts.

Xcode log output from previous version:
```
Loading network plugin
2021-07-22 11:32:00.294465-0400 App[84477:30412126] CAPKeyboard: resize mode - native
⚡️  Loading app at http://192.168.2.3:5001...
2021-07-22 11:32:00.385756-0400 App[84477:30412126] WF: === Starting WebFilter logging for process App
2021-07-22 11:32:00.385873-0400 App[84477:30412126] WF: _userSettingsForUser : (null)
2021-07-22 11:32:00.385929-0400 App[84477:30412126] WF: _WebFilterIsActive returning: NO
APP ACTIVE
Reachable via WiFi
⚡️  WebView loaded
⚡️  WebView loaded
```

Xcode log out from v2.0:
```
2021-07-22 11:22:54.420398-0400 App[83598:30400636] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/tajima/Library/Developer/CoreSimulator/Devices/901D5A60-1082-4B25-9130-029983B267AA/data/Containers/Data/Application/9BA8AC23-9CAD-4A59-B122-E81DF7591159/Library/Cookies/com.svelte.capacitor.binarycookies
⚡️  Loading app at capacitor://localhost...
2021-07-22 11:22:54.635729-0400 App[83598:30400636] WF: === Starting WebFilter logging for process App
2021-07-22 11:22:54.635796-0400 App[83598:30400636] WF: _userSettingsForUser : (null)
2021-07-22 11:22:54.635854-0400 App[83598:30400636] WF: _WebFilterIsActive returning: NO
⚡️  WebView loaded
```

My ```capacitor.config.json```:
```
{
	"appId": "com.svelte.capacitor",
	"appName": "Svelte Capacitor",
	"bundledWebRuntime": false,
	"npmClient": "npm",
	"webDir": "public",
	"plugins": {
		"SplashScreen": {
			"launchShowDuration": 0
		}
	},
	"cordova": {},
	"server": {
		"server": {
			"url": "http://192.168.2.3:5001",
			"cleartext": true
		}
	}
}
```
The only thing changed was I added my ip in the server part.

Not sure if I am doing something wrong, or something is not configured properly, for if there is a script missing from ```package.json```?

**Comment by jkt3000** [comment] 2021-07-22 17:10
Another difference I noticed between v2.0 and the previous was that in the IOS simulator, I would get a modal on the simulator saying "using app server http://x.x.x.x:5001". I get no such message in v2.0 in the simulator.

**Comment by macleod-ee** [comment] 2021-07-22 17:50
That's interesting since I don't seem to be having that problem, sadly.

Could you try adding the IP address that vite gives you for your Network? It will run a few different servers ports for different things,

Here's how: launch the dev command (npm run dev:ios), snag the network IP that vite will show up with, stop the server, and add that IP address to the server.url, ans try running that command again and tell me if that changes anything?

**Comment by jkt3000** [comment] 2021-07-22 19:06
I just tried on a fresh install of the repo.

cloned the repo
npm install
npm run dev:start and verified webpage showed spash screen
stop server
npx cap add ios
npm run dev:ios and launched simulator - showed a blank screen
- at this point capacitor.config.json is untouched, so server.url would be "change-me:5001". 
- vite network address shown is:
```

  vite v2.4.3 dev server running at:

  > Local:    http://localhost:5000/
  > Network:  http://192.168.2.3:5000/
```

Stopped the server, and updated `/capacitor.config.json` with network address shown.

npm run dev:ios

verified that `/ios/App/App/capacitor.config.json` was updated/copied from `/capacitor.config.json`

again launched ios simulator. Simulator again shows blank screen.

Log of xcode:
```
2021-07-22 14:47:06.316119-0400 App[95596:30636074] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/tajima/Library/Developer/CoreSimulator/Devices/CAEE6513-6C87-49FD-A207-1AD0EEDE8891/data/Containers/Data/Application/D12BFF0A-1F3A-4D25-A969-8CBFB70A6EDD/Library/Cookies/com.svelte.capacitor.binarycookies
⚡️  Loading app at capacitor://localhost...
2021-07-22 14:47:06.543176-0400 App[95596:30636074] WF: === Starting WebFilter logging for process App
2021-07-22 14:47:06.543243-0400 App[95596:30636074] WF: _userSettingsForUser : (null)
2021-07-22 14:47:06.543299-0400 App[95596:30636074] WF: _WebFilterIsActive returning: NO
⚡️  WebView loaded
```

Interesting to note the line `Loading app at capacitor://localhost...` Not sure where it's getting that, since that is not what is in server.url in `capacitor.config.json`

**Comment by macleod-ee** [comment] 2021-07-22 19:11
Yeah, this is strange to me. Have you tried the [troubleshooting guide](https://capacitorjs.com/docs/ios/troubleshooting) on Capacitor? 

A section that seemed most apt is this one:

> Cleaning and rebuilding can fix a number of build issues. Navigate to Product -> Clean Build Folder in the Xcode menu to clean your current build.

**Comment by jkt3000** [comment] 2021-07-22 19:14
Actually, I'm noticing a typo compared to previous versions:

https://github.com/drannex42/svelte-capacitor/blob/5a3518eadc9caa7e891ee4ac5e0af96add555b94/capacitor.config.json#L13

The change looks like server server got added:

https://github.com/drannex42/svelte-capacitor/commit/c9bfd381cbc799cb3e576b959e6957f1ddbae128#diff-ec2b53f1220a8bca613b0f050e250e7869ef60b2c5bc3de7cbb55f98ad0999f4

Will change and see if that fixes it

**Comment by macleod-ee** [comment] 2021-07-22 19:19
That should fix it! I can't believe I overlooked that before publishing. Likely related to the revert I did that went back a few commits.

**Comment by jkt3000** [comment] 2021-07-22 19:20
Lol.
Ok, so there was an error in the `capacitor.config.json`

```
"server": {
  "server": {
    "url": "http://192.168.2.3:5000/",
    "cleartext": true
  }
}
```
Should be:
```
  "server": {
    "url": "http://192.168.2.3:5000/",
    "cleartext": true
  }
```

**Comment by macleod-ee** [comment] 2021-07-22 19:21
I went ahead and fixed that, good catch there.

**Comment by jkt3000** [comment] 2021-07-22 19:21
Nice. One final thing, it should be port 5000 now, not 5001.

**Comment by macleod-ee** [comment] 2021-07-22 19:25
Would you say the issue is fixed? I'll close the issue if it is.

**Comment by jkt3000** [comment] 2021-07-22 19:27
yes, that fixes it for me.

**Closed as completed** 2021-07-22 19:30 UTC
